### ISSUE TITLE
Attaching APK files to the release

### ISSUE THREAD

**Issue by kuhlmannmarkus** [openziti/ziti-tunnel-android#153]
Would it be possible to attach APK files to the releases? At the moment there is only the AAB package. It is possible to extract the APKs, but then one has to sign them before installing.

**Comment by TheDarkula** [comment]
@kuhlmannmarkus This would be a great addition, as it would allow installing directly with [Obtainium](https://github.com/ImranR98/Obtainium).
It also benefits those who do not use the Play Store, like GrapheneOS users.

**Comment by TheDarkula** [comment]
Also, @dovholuknf, your Mattermost workflow is [failing](https://github.com/openziti/ziti-tunnel-android/actions/runs/5428627868).

**Comment by dovholuknf** [comment]
Wow, it sure is! I'll see if I can fix that. Thanks.

**Comment by TheDarkula** [comment]
Glad to help :)

**Comment by dovholuknf** [comment]
fixed it. thanks for letting me/us know. @ekoby will probably have to comment on the APK ask

**Comment by TheDarkula** [comment]
Sure thing!

**Comment by kuhlmannmarkus** [comment]
Awesome! Thank you so much!

**Comment by TheDarkula** [comment]
@ekoby Thank you, indeed!
There is a failure in the webhook action, though: https://github.com/openziti/ziti-tunnel-android/actions/runs/5836422783

**Comment by dovholuknf** [comment]
@ekoby. Did you see the action failure?
