### ISSUE TITLE
Android 14 - DNS stops working

### ISSUE THREAD

**Issue by jonasgroenke** [openziti/ziti-tunnel-android#196]
Hey,
I got an issue with the android app. When I stay connected with the vpn, after a while the DNS stops working and in the browser (chrome) I only get dns errors.
Reconnect the vpn also doesn't help and the only way I can fix it is by hardly killing the app over the settings and restarting it.

It can be reproduced by connecting to the vpn and then closing the app via the app overview, while the vpn is still connected. After a couple of seconds / minutes (the time varies a bit), the DNS stops working.

I already tried to disable the battery optimization and allow the background activity, but it seems not to help.

Maybe there are some changes in the latest android version and the background service get stopped for some reason.
I have this behavior on two android 14 Samsung devices.

Kind regards
Jonas

**Comment by ekoby** [comment]
can you please attach or email the feedback bundle?

**Comment by ekoby** [comment]
@jonasgroenke 
new release is now available via Beta program. 
You can join and try it here: https://play.google.com/store/apps/details?id=org.openziti.mobile

Feel free to submit feedback and/or report any issues here.

**Comment by ekoby** [comment]
fixed in latest releases with more robust upstream DNS handling #199
